#!/usr/bin/env bash

empty_portage_tree() {
	if [ -d ""$portagedir"/.git" ] ; then
		find "$portagedir" -mindepth 1 -name "packages" -prune -o -name "distfiles" -prune -o -exec rm -rf {} \; > /dev/null 2>&1
	fi
}

reset_portage_config() {
	rm ""$confdir"/make.conf"
	rm ""$confdir"/make.profile"
	rm "$confdir"
	rm -rf "$clonedir"
}

fetch_portage_config() {
	pushd /opt > /dev/null 2>&1
	git clone https://gitlab.com/redcore/redcore-build.git > /dev/null 2>&1
	popd > /dev/null 2>&1
}

main () {
	empty_portage_tree
	reset_portage_config
	fetch_portage_config
}
main
