#!/usr/bin/env bash
# Say Hello to Vasile, a modular script to build Redcore Linux packages && ISO images using a clean squashfs + overlayfs chroot
# Main author : Ghiunhan Mamut (aka V3n3RiX)
# Dependencies : kernel built with squashfs + overlayfs + loopback support && sys-fs/grub:2 && sys-fs/squashfs-tools && dev-libs/libisoburn && sys-fs/mtools
#

# Import our variables and functions

source /usr/lib/vasile/libvasile

# Vasile need root privileges and a proper kernel to run
# Also, running it in live mode is a really bad idea

checkroot
checkiflive
kernelconfig


case $1 in
	--makepkg)
		makepkg
		;;
	--makeiso)
		makeiso
		;;
	--resetmode)
		source /usr/share/vasile/resetmode
		;;
	--binmode)
		source /usr/share/vasile/resetmode
		source /usr/share/vasile/binmode
		;;
	--mixedmode)
		source /usr/share/vasile/resetmode
		source /usr/share/vasile/mixedmode
		;;
	--srcmode)
		source /usr/share/vasile/resetmode
		source /usr/share/vasile/srcmode
		;;
	--help)
		einfo "Usage: vasile [options]"
		einfo ""
		einfo "Options:"
		einfo "--makepkg : build package/target in a clean squashed core"
		einfo "--makeiso : build iso based on clean squashed core + targets"
		einfo "--resetmode : reset Redcore Linux system state - You're on your own, you've been warned!"
		einfo "--binmode : switch Redcore Linux system state to binary only mode"
		einfo "--mixedmode : switch Redcore Linux system state to mixed (binary/source) mode"
		einfo "--srcmode : switch Redcore Linux system state to source only mode (full Gentoo mode)"
		einfo "--help : display this help and exit"
		;;
	*)
		eerror "error: no operation specified, use --help for help"
		;;
esac

exit 0
